<table cellpadding="0" cellspacing="0">
    <thead>
    <tr>
        <td>Дата</td>
        <td>Ник</td>
        <td>Статус</td>
        <td>Сумма</td>
        <td>%</td>
    </tr>
    </thead>
    <tr>
        <td>11.10.2017</td>
        <td>proorder</td>
        <td>Активен</td>
        <td><span>1254.00</span><span>&#8381;</span></td>
        <td>7%</td>
    </tr>
    <tr>
        <td>11.10.2017</td>
        <td>proorder</td>
        <td>Активен</td>
        <td><span>1254.00</span><span>&#8381;</span></td>
        <td>7%</td>
    </tr>
    <tr>
        <td>11.10.2017</td>
        <td>proorder</td>
        <td>Активен</td>
        <td><span>1254.00</span><span>&#8381;</span></td>
        <td>7%</td>
    </tr>
</table>